<?php
/**
 * @package    Joomla.Component.Builder
 *
 * @created    25th August, 2026
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace VDM\Joomla\Componentbuilder\Extrusion\Resolver;


use VDM\Joomla\Componentbuilder\Extrusion\Registry\Report;
use VDM\Joomla\Utilities\Component\Helper;


/**
 * The permission actions an admin view record may hold.
 * 
 * A view's permissions are a list field, and JCB's own form declares which
 * actions that list offers. An action outside it cannot be selected by hand
 * and is not displayed either -- the browser shows the first option in its
 * place -- so a run that stores one has written a row nobody can read.
 * 
 * The offered set is read from that form rather than repeated here, because
 * the form is where JCB states it. Everything else a component's access rules
 * name is generated by the compiler from the view's own switches (batch on
 * every admin view, version with history, export and import with port, the
 * menu and dashboard actions with their switches), and belongs to those
 * switches rather than to this list.
 * 
 * @since 6.1.8
 */
final class Actions
{
	/**
	 * The Report Registry.
	 *
	 * @var    Report
	 * @since  6.1.8
	 */
	protected Report $report;

	/**
	 * The form that declares the offered actions.
	 *
	 * @var    string
	 * @since  6.1.8
	 */
	protected string $form;

	/**
	 * The offered actions, once read.
	 *
	 * @var    array<string, bool>|null
	 * @since  6.1.8
	 */
	protected ?array $offered = null;

	/**
	 * Constructor.
	 *
	 * @param   Report       $report  The run report registry.
	 * @param   string|null  $form    The form declaring the actions, or null to find it.
	 *
	 * @since   6.1.8
	 */
	public function __construct(Report $report, ?string $form = null)
	{
		$this->report = $report;
		$this->form = $form ?? $this->located();
	}

	/**
	 * Every action a permission row may name.
	 *
	 * @return  array<int, string>  The offered actions, in the order the form offers them.
	 * @since   6.1.8
	 */
	public function offered(): array
	{
		return array_keys($this->read());
	}

	/**
	 * Whether one action may be stored in a permission row.
	 *
	 * @param   string  $action  The action.
	 *
	 * @return  bool  True when the form offers it.
	 * @since   6.1.8
	 */
	public function offers(string $action): bool
	{
		return isset($this->read()[strtolower(trim($action))]);
	}

	/**
	 * The offered actions, read once from the form.
	 *
	 * @return  array<string, bool>  The offered actions.
	 * @since   6.1.8
	 */
	protected function read(): array
	{
		if ($this->offered !== null)
		{
			return $this->offered;
		}

		$this->offered = [];

		if ($this->form === '' || !is_file($this->form))
		{
			$this->report->set('failed.read.permission_actions', $this->form);

			return $this->offered;
		}

		$xml = @simplexml_load_file($this->form);

		if ($xml === false)
		{
			$this->report->set('failed.read.permission_actions', $this->form);

			return $this->offered;
		}

		foreach ($xml->xpath('//field[@name="action"]/option') ?: [] as $option)
		{
			$value = strtolower(trim((string) $option['value']));

			if ($value !== '')
			{
				$this->offered[$value] = true;
			}
		}

		return $this->offered;
	}

	/**
	 * The form JCB itself uses for an admin view's permissions.
	 *
	 * @return  string  The absolute path, or an empty string.
	 * @since   6.1.8
	 */
	protected function located(): string
	{
		if (!defined('JPATH_ADMINISTRATOR'))
		{
			return '';
		}

		$code = 'componentbuilder';

		try
		{
			// the running component is the one whose form states this list;
			// a run with no application to ask is JCB's own either way
			$code = (string) (Helper::getCode(null, $code) ?? $code);
		}
		catch (\Throwable $error)
		{
			$code = 'componentbuilder';
		}

		return JPATH_ADMINISTRATOR . '/components/com_' . $code . '/forms/admin_view.xml';
	}
}

