ALTER TABLE `#__componentbuilder_component` ADD `add_php_postflight_install` TINYINT(1) NOT NULL DEFAULT '0' AFTER `add_php_helper_site`,
ADD `add_php_method_uninstall` TINYINT(1) NOT NULL DEFAULT '0' AFTER `add_php_postflight_install`,
ADD `add_php_postflight_update` TINYINT(1) NOT NULL DEFAULT '0' AFTER `add_php_method_uninstall`,
ADD `add_php_preflight_install` TINYINT(1) NOT NULL DEFAULT '0' AFTER `add_php_postflight_update`,
ADD `add_php_preflight_update` TINYINT(1) NOT NULL DEFAULT '0' AFTER `add_php_preflight_install`,
ADD `php_postflight_install` MEDIUMTEXT NOT NULL AFTER `php_helper_site`,
ADD `php_method_uninstall` MEDIUMTEXT NOT NULL AFTER `php_postflight_install`,
ADD `php_postflight_update` MEDIUMTEXT NOT NULL AFTER `php_method_uninstall`,
ADD `php_preflight_install` MEDIUMTEXT NOT NULL AFTER `php_postflight_update`,
ADD `php_preflight_update` MEDIUMTEXT NOT NULL AFTER `php_preflight_install`;
