CREATE TABLE IF NOT EXISTS `#__componentbuilder_power` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`add_head` TINYINT(1) NOT NULL DEFAULT 0,
	`description` TEXT NOT NULL,
	`extends` VARCHAR(36) NOT NULL DEFAULT '',
	`extends_custom` VARCHAR(64) NOT NULL DEFAULT '',
	`guid` VARCHAR(36) NOT NULL DEFAULT '',
	`head` TEXT NOT NULL,
	`implements` TEXT NULL,
	`implements_custom` VARCHAR(1024) NOT NULL DEFAULT '',
	`load_selection` TEXT NOT NULL,
	`main_class_code` MEDIUMTEXT NOT NULL,
	`method_selection` TEXT NOT NULL,
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`namespace` VARCHAR(255) NOT NULL DEFAULT '',
	`power_version` CHAR(64) NOT NULL DEFAULT '',
	`property_selection` TEXT NOT NULL,
	`system_name` VARCHAR(255) NOT NULL DEFAULT '',
	`type` VARCHAR(64) NOT NULL DEFAULT '',
	`use_selection` TEXT NOT NULL,
	`params` text NULL,
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	PRIMARY KEY  (`id`),
	KEY `idx_system_name` (`system_name`),
	KEY `idx_namespace` (`namespace`),
	KEY `idx_type` (`type`),
	KEY `idx_implements_custom` (`implements_custom`),
	KEY `idx_extends_custom` (`extends_custom`),
	KEY `idx_guid` (`guid`),
	KEY `idx_name` (`name`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
