CREATE TABLE IF NOT EXISTS `#__componentbuilder_online_code` (
	`url` VARCHAR(255) NOT NULL DEFAULT '',
	`hash` VARCHAR(64) NOT NULL DEFAULT '',
	PRIMARY KEY  (`url`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
