CREATE TABLE IF NOT EXISTS `#__componentbuilder_external_code` (
	`target` VARCHAR(255) NOT NULL DEFAULT '',
	`hash` VARCHAR(64) NOT NULL DEFAULT '',
	PRIMARY KEY  (`target`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
