<?php
/**
 * @package    Joomla.Component.Builder
 *
 * @created    4th September, 2022
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace VDM\Joomla\Database;


use Joomla\CMS\Date\Date;
use VDM\Joomla\Database\DefaultTrait;
use VDM\Joomla\Utilities\MathHelper;
use VDM\Joomla\Utilities\ArrayHelper;
use VDM\Joomla\Interfaces\Database\InsertInterface;
use VDM\Joomla\Abstraction\Versioning;


/**
 * Database Insert Class
 * 
 * @since 3.2.0
 */
final class Insert extends Versioning implements InsertInterface
{
	/**
	 * Default Switch
	 *
	 * @since 5.1.1
	 */
	use DefaultTrait;

	/**
	 * The history guid tracker bucket
	 *
	 * @var      array
	 * @since  5.1.1
	 **/
	protected array $historyGuid = [];

	/**
	 * The inserted id tracker bucket
	 *
	 * @var      array
	 * @since  5.1.4
	 **/
	protected array $insertids = [];

	/**
	 * Get the auto-increment IDs generated by the most recent INSERT batch.
	 *
	 * This method returns the ordered list of auto-increment IDs calculated
	 * from the last executed multi-row INSERT operation.
	 *
	 * Behavioral notes:
	 * - IDs are only valid immediately after an INSERT operation.
	 * - The order of IDs matches the insertion order.
	 * - AUTO_INCREMENT values are assumed to be sequential within a single
	 *   INSERT statement (as guaranteed by Joomla-supported databases).
	 * - When `$reset` is enabled, the internal ID bucket is cleared after
	 *   the values are retrieved.
	 *
	 * @param   bool  $reset  Whether to reset the internal insert ID bucket
	 *                        after retrieval.
	 *
	 * @return  array<int|string>  The generated auto-increment IDs.
	 *
	 * @since   5.1.4
	 */
	public function insertids(bool $reset = false): array
	{
		$ids = $this->insertids;

		if ($reset && $ids !== [])
		{
			$this->insertids = [];
		}

		return $ids;
	}

	/**
	 * Insert rows to the database (with remapping and filtering columns option)
	 *
	 * @param   array    $data      Dataset to store in database [array of arrays (key => value)]
	 * @param   string   $table     The table where the data is being added
	 * @param   array    $columns   Data columns for remapping and filtering
	 *
	 * @return  bool
	 * @since   3.2.0
	 **/
	public function rows(array $data, string $table, array $columns = []): bool
	{
		if (!ArrayHelper::check($data))
		{
			return false;
		}

		if ($columns === [])
		{
			$columns = $this->getArrayColumns($data);
		}

		return ($columns === []) ? false : $this->insert($data, $table, $columns, true);
	}

	/**
	 * Insert items to the database (with remapping and filtering columns option)
	 *
	 * @param   array    $data         Data to store in database (array of objects)
	 * @param   string   $table        The table where the data is being added
	 * @param   array    $columns      Data columns for remapping and filtering
	 *
	 * @return  bool
	 * @since   3.2.0
	 **/
	public function items(array $data, string $table, array $columns = []): bool
	{
		if (!ArrayHelper::check($data))
		{
			return false;
		}

		if ($columns === [])
		{
			$columns = $this->getObjectsColumns($data);
		}

		return ($columns === []) ? false : $this->insert($data, $table, $columns, false);
	}

	/**
	 * Insert row to the database
	 *
	 * @param   array    $data      Dataset to store in database (key => value)
	 * @param   string   $table     The table where the data is being added
	 *
	 * @return  bool
	 * @since   3.2.0
	 **/
	public function row(array $data, string $table): bool
	{
		return $this->rows([$data], $table);
	}

	/**
	 * Insert item to the database
	 *
	 * @param   object    $data     Dataset to store in database (key => value)
	 * @param   string   $table     The table where the data is being added
	 *
	 * @return  bool
	 * @since   3.2.0
	 **/
	public function item(object $data, string $table): bool
	{
		return $this->items([$data], $table);
	}

	/**
	 * Get columns from data array
	 *
	 * @param   array   $data   Data array
	 *
	 * @return  array
	 * @since   3.2.0
	 **/
	protected function getArrayColumns(array &$data): array
	{
		$row = array_values($data)[0];

		if (!ArrayHelper::check($row))
		{
			return [];
		}

		$columns = array_keys($row);

		return array_combine($columns, $columns);
	}

	/**
	 * Get columns from data objects
	 *
	 * @param   array   $data   Data objects
	 *
	 * @return  array
	 * @since   3.2.0
	 **/
	protected function getObjectsColumns(array &$data): array
	{
		$row = array_values($data)[0];

		if (!is_object($row))
		{
			return [];
		}

		$columns = get_object_vars($row);

		return array_combine(array_keys($columns), array_keys($columns));
	}

	/**
	 * Insert data into the database
	 *
	 * @param   array   $data      Data to store in database
	 * @param   string  $table     The table where the data is being added
	 * @param   array   $columns   Data columns for remapping and filtering
	 * @param   bool    $isArray   Whether the data is an array of arrays or an array of objects
	 *
	 * @return  bool
	 * @since   3.2.0
	 **/
	protected function insert(array &$data, string $table, array $columns, bool $isArray): bool
	{
		// set joomla default columns
		$add_created = false;
		$add_created_by = false;
		$add_version = false;
		$add_published = false;

		// check if we should load the defaults
		if ($this->defaults)
		{
			// get the date
			$date = (new Date())->toSql();

			if (!isset($columns['created']))
			{
				$columns['created'] = ' (o_O) ';
				$add_created = true;
			}

			if (!isset($columns['created_by']))
			{
				$columns['created_by'] = ' (o_O) ';
				$add_created_by = true;
			}

			if (!isset($columns['version']))
			{
				$columns['version'] = ' (o_O) ';
				$add_version = true;
			}

			if (!isset($columns['published']))
			{
				$columns['published'] = ' (o_O) ';
				$add_published = true;
			}
			// the (o_O) prevents an empty value from being loaded
		}

		// set history vars
		$this->entity = $this->getTableEntityName($table);
		$this->historyGuid = [];
		$this->insertids = [];

		// get a query object
		$query = $this->db->createQuery();
		$table = $this->getTable($table);

		// set the query targets
		$query->insert($this->db->quoteName($table))->columns($this->db->quoteName(array_keys($columns)));

		// limiting factor on the amount of rows to insert before we reset the query
		$limit = 300;

		// to calculate the rows added
		$row_counter = 0;

		// set the insert values
		foreach ($data as $nr => $value)
		{
			// check the limit
			if ($limit <= 1)
			{
				// execute and reset the query
				$this->db->setQuery($query);
				$this->db->execute();

				// set row ids
				$this->setInsertIds($row_counter);

				// reset the counter
				$row_counter = 0;

				// reset limit
				$limit = 300;

				// get a query object
				$query = $this->db->createQuery();

				// set the query targets
				$query->insert($this->db->quoteName($table))->columns($this->db->quoteName(array_keys($columns)));
			}

			$row = [];
			foreach ($columns as $column => $key)
			{
				if (' (o_O) ' === $key)
				{
					continue;
				}

				$val = ($isArray && isset($value[$key])) ? $value[$key]
					: ((!$isArray && isset($value->{$key})) ? $value->{$key} : '');

				// we can only set history if we have a guid in the data set
				if ($column === 'guid' && !empty($this->entity) && $this->history && !empty($val))
				{
					$this->historyGuid[$val] = 1;
				}

				$row[] = $this->quote($val);
			}

			// set joomla default columns
			if ($add_created)
			{
				$row[] = $this->db->quote($date);
			}

			if ($add_created_by)
			{
				$row[] = $this->userId;
			}

			if ($add_version)
			{
				$row[] = 1;
			}

			if ($add_published)
			{
				$row[] = 1;
			}

			// add to query
			$query->values(implode(',', $row));

			// count the row
			$row_counter++;

			// decrement the limiter
			$limit--;

			// clear the data from memory
			unset($data[$nr]);
		}

		// execute the final query
		$this->db->setQuery($query);
		$this->db->execute();

		// set row ids
		$this->setInsertIds($row_counter);

		// Track version history (prefer GUIDs, fallback to IDs)
		if ($this->history && !empty($this->entity))
		{
			$this->trackHistory($table);
		}

		// always reset the switch's
		$this->defaults()->history();

		return true;
	}

	/**
	 * Store all auto-increment IDs generated by the last multi-row INSERT.
	 *
	 * This method calculates the ID range produced by the most recent
	 * INSERT statement and appends them to the internal history ID bucket.
	 *
	 * Important guarantees:
	 * - IDs are sequential within a single INSERT statement
	 * - insertid() returns the FIRST generated ID
	 * - The number of generated IDs equals the number of inserted rows
	 *
	 * BIGINT safety:
	 * - If the database returns the insert ID as a string, MathHelper::bc()
	 *   is used to increment the value safely.
	 * - If bcmath is unavailable, MathHelper falls back to native operators.
	 *
	 * @param   int  $rowsInserted  The number of rows inserted by the last query.
	 *
	 * @return  void
	 *
	 * @since   5.1.4
	 */
	protected function setInsertIds(int $rowsInserted): void
	{
		if ($rowsInserted < 1)
		{
			return;
		}

		$firstId = $this->db->insertid();

		if (empty($firstId))
		{
			return;
		}

		// BIGINT-safe path
		if (is_string($firstId))
		{
			for ($i = 0; $i < $rowsInserted; $i++)
			{
				$this->insertids[] = MathHelper::bc('add', $firstId, $i, 0);
			}

			return;
		}

		// Native integer path
		for ($i = 0; $i < $rowsInserted; $i++)
		{
			$this->insertids[] = $firstId + $i;
		}
	}

	/**
	 * Track history records for the current entity.
	 *
	 * Resolution priority:
	 * 1. GUID-based lookup (preferred)
	 * 2. ID-based fallback
	 *
	 * History tracking errors are intentionally ignored to ensure
	 * persistence operations never fail because of history handling.
	 *
	 * @param  string  $table  The full table name.
	 *
	 * @return void
	 * @since  5.1.1
	 */
	protected function trackHistory(string $table): void
	{
		try
		{
			// Attempt GUID-based history resolution first
			if ($this->historyGuid !== [])
			{
				$guids = array_keys($this->historyGuid);

				if ($guids !== [])
				{
					$query = $this->db->createQuery()
						->select($this->db->quoteName('id'))
						->from($this->db->quoteName($table))
						->where(
							$this->db->quoteName('guid') . ' IN (' .
							implode(',', array_map(fn($v) => $this->quote($v), $guids)) .
							')'
						);

					$this->db->setQuery($query);
					$this->db->execute();

					if ($this->db->getNumRows())
					{
						$this->setMultipleHistory($this->db->loadColumn());
						return;
					}
				}
			}

			// Fallback to ID-based history tracking
			if ($this->insertids !== [])
			{
				$this->setMultipleHistory($this->insertids);
			}
		}
		catch (\Throwable $e)
		{
			// History tracking must never block persistence
		}
	}
}

