DROP TABLE IF EXISTS `#__costbenefitprojection_company`;
DROP TABLE IF EXISTS `#__costbenefitprojection_service_provider`;
DROP TABLE IF EXISTS `#__costbenefitprojection_country`;
DROP TABLE IF EXISTS `#__costbenefitprojection_causerisk`;
DROP TABLE IF EXISTS `#__costbenefitprojection_health_data`;
DROP TABLE IF EXISTS `#__costbenefitprojection_scaling_factor`;
DROP TABLE IF EXISTS `#__costbenefitprojection_intervention`;
DROP TABLE IF EXISTS `#__costbenefitprojection_currency`;
DROP TABLE IF EXISTS `#__costbenefitprojection_help_document`;
